# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: 'ba812dd7-4b73-4928-95b0-b7afcd79efc3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KubeRG'
    location: 'Qatar Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/asifgohar/ARMPipeline-repo/200348d77dd9395fe69759111d5edbeddb6da42a/create_web_app/azuredeploy.json'
    overrideParameters: '-projectname ARMPipeline-repo'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
